
[build-system]
requires = [
  "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "windArd"
version = "0.0.0a1"
authors = [
  {name = "Cory Frontin", email = "cory.frontin@nrel.gov"},
  {name = "Rafael Mudafort", email = "rafael.mudafort@nrel.gov"},
]
description = "A package for multidisciplinary and/or multifidelity wind farm design"
readme= "README.md"
requires-python = ">=3.10"
# url =
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Development Status :: 3 - Alpha",
]
# license_files = LICENSE
dependencies = [
  "numpy",
  "floris",
  "wisdem",
  "marmot-agents",
  "openmdao",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
]

# [tool.setuptools]
# py_modules = ["windard"]

[tool.setuptools.packages.find]
# where = ["."]  # list of folders that contain the packages (["."] by default)
# include = ["windard"]  # package names should match these glob patterns (["*"] by default)
exclude = ["assets"]  # exclude packages matching these glob patterns (empty by default)
# namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[options]
# package_dir == tools_cvf
packages = "windard"
python_requires = ">= 3.8"
