name: Run Example Scripts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-example:
    strategy:
      matrix:
        python-version: [3.12] # ["3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Install Ard
      run: |
        pip install .[dev]

    - name: Run examples
      shell: python
      run: |
        import pathlib
        import subprocess
        for example_dir in pathlib.Path("examples").iterdir():
          if example_dir.is_dir():
            print(f"RUNNING {example_dir}")
            for pyfile in example_dir.glob("*.py"):
              subprocess.run(["python", str(pyfile)], check=True)
