name: Python System Tests with Coverage

on:
  push:
    branches:
      - main
      - develop
      - system_testing
  pull_request:
    branches:
      - main
      - develop
      - system_testing

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Install Ard
      run: |
        pip install .[dev]

    - name: Run system tests with coverage
      run: |
        pytest --cov=ard --cov-fail-under=50 test/system
        # pytest --cov=ard --cov-fail-under=80 test/system

    # - name: Upload coverage report
    #   uses: codecov/codecov-action@v2
    #   with:
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: codecov-umbrella

